"""create initial tables

Revision ID: 05ec64d9ea5c
Revises: 
Create Date: 2026-09-30 16:46:13.452158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ec64d9ea5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('file_report', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_company_currency_iso4217_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('public_id', name=op.f('uq_company_public_id'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('public_id', name=op.f('uq_users_public_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('auth',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_email')),
    sa.UniqueConstraint('public_id', name=op.f('uq_auth_public_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_auth_user_id'))
    )
    op.create_table('customer',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_customer_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('id', 'company_id', name='uq_customer_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_customer_public_id'))
    )
    op.create_index(op.f('ix_customer_company_id'), 'customer', ['company_id'], unique=False)
    op.create_table('schedule',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_schedule_end_after_start')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_schedule_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule')),
    sa.UniqueConstraint('id', 'company_id', name='uq_schedule_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_schedule_public_id'))
    )
    op.create_index(op.f('ix_schedule_company_id'), 'schedule', ['company_id'], unique=False)
    op.create_table('service',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_service_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
    sa.UniqueConstraint('company_id', 'name', name='uq_service_company_id_name'),
    sa.UniqueConstraint('id', 'company_id', name='uq_service_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_service_public_id'))
    )
    op.create_index(op.f('ix_service_company_id'), 'service', ['company_id'], unique=False)
    op.create_table('team',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_team_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team')),
    sa.UniqueConstraint('id', 'company_id', name='uq_team_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_team_public_id'))
    )
    op.create_index(op.f('ix_team_company_id'), 'team', ['company_id'], unique=False)
    op.create_table('employee',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_employee_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id', 'company_id'], ['team.id', 'team.company_id'], name='fk_employee_team_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employee_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee')),
    sa.UniqueConstraint('id', 'company_id', name='uq_employee_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_employee_public_id')),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_employee_user_id_company_id')
    )
    op.create_index(op.f('ix_employee_company_id'), 'employee', ['company_id'], unique=False)
    op.create_index('ix_employee_team_id', 'employee', ['team_id'], unique=False)
    op.create_index(op.f('ix_employee_user_id'), 'employee', ['user_id'], unique=False)
    op.create_table('property',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='property_size', native_enum=False, length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("size IN ('small', 'medium', 'large')", name=op.f('ck_property_ck_property_property_size')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_property_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id', 'company_id'], ['customer.id', 'customer.company_id'], name='fk_property_customer_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property')),
    sa.UniqueConstraint('id', 'company_id', name='uq_property_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_property_public_id'))
    )
    op.create_index(op.f('ix_property_company_id'), 'property', ['company_id'], unique=False)
    op.create_index('ix_property_customer_id', 'property', ['customer_id'], unique=False)
    op.create_table('employee_registry',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('hour_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hour_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('extra_hours >= 0', name=op.f('ck_employee_registry_extra_hours_non_negative')),
    sa.CheckConstraint('hour_end IS NULL OR hour_end > hour_start', name=op.f('ck_employee_registry_hour_end_after_start')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_employee_registry_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id', 'company_id'], ['employee.id', 'employee.company_id'], name='fk_employee_registry_employee_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_registry')),
    sa.UniqueConstraint('public_id', name=op.f('uq_employee_registry_public_id'))
    )
    op.create_index(op.f('ix_employee_registry_company_id'), 'employee_registry', ['company_id'], unique=False)
    op.create_index('ix_employee_registry_employee_id', 'employee_registry', ['employee_id'], unique=False)
    op.create_table('work_order',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('schedule_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scheduled', 'in_progress', 'completed', 'cancelled', name='work_order_status', native_enum=False, length=20), server_default='pending', nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'scheduled', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_work_order_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_work_order_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id', 'company_id'], ['property.id', 'property.company_id'], name='fk_work_order_property_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['schedule_id', 'company_id'], ['schedule.id', 'schedule.company_id'], name='fk_work_order_schedule_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'company_id'], ['team.id', 'team.company_id'], name='fk_work_order_team_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order')),
    sa.UniqueConstraint('id', 'company_id', name='uq_work_order_id_company_id'),
    sa.UniqueConstraint('public_id', name=op.f('uq_work_order_public_id'))
    )
    op.create_index(op.f('ix_work_order_company_id'), 'work_order', ['company_id'], unique=False)
    op.create_index('ix_work_order_company_id_status', 'work_order', ['company_id', 'status'], unique=False)
    op.create_index('ix_work_order_property_id', 'work_order', ['property_id'], unique=False)
    op.create_index('ix_work_order_schedule_id', 'work_order', ['schedule_id'], unique=False)
    op.create_index('ix_work_order_team_id', 'work_order', ['team_id'], unique=False)
    op.create_table('work',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hours', sa.Interval(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('payment >= 0', name=op.f('ck_work_payment_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_work_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id', 'company_id'], ['service.id', 'service.company_id'], name='fk_work_service_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id', 'company_id'], ['work_order.id', 'work_order.company_id'], name='fk_work_work_order_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work')),
    sa.UniqueConstraint('public_id', name=op.f('uq_work_public_id'))
    )
    op.create_index(op.f('ix_work_company_id'), 'work', ['company_id'], unique=False)
    op.create_index('ix_work_service_id', 'work', ['service_id'], unique=False)
    op.create_index('ix_work_work_order_id', 'work', ['work_order_id'], unique=False)
    op.create_table('work_order_photo',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_work_order_photo_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id', 'company_id'], ['employee.id', 'employee.company_id'], name='fk_work_order_photo_employee_same_company', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id', 'company_id'], ['work_order.id', 'work_order.company_id'], name='fk_work_order_photo_work_order_same_company', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_photo')),
    sa.UniqueConstraint('public_id', name=op.f('uq_work_order_photo_public_id'))
    )
    op.create_index(op.f('ix_work_order_photo_company_id'), 'work_order_photo', ['company_id'], unique=False)
    op.create_index('ix_work_order_photo_employee_id', 'work_order_photo', ['employee_id'], unique=False)
    op.create_index('ix_work_order_photo_work_order_id', 'work_order_photo', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_order_photo_work_order_id', table_name='work_order_photo')
    op.drop_index('ix_work_order_photo_employee_id', table_name='work_order_photo')
    op.drop_index(op.f('ix_work_order_photo_company_id'), table_name='work_order_photo')
    op.drop_table('work_order_photo')
    op.drop_index('ix_work_work_order_id', table_name='work')
    op.drop_index('ix_work_service_id', table_name='work')
    op.drop_index(op.f('ix_work_company_id'), table_name='work')
    op.drop_table('work')
    op.drop_index('ix_work_order_team_id', table_name='work_order')
    op.drop_index('ix_work_order_schedule_id', table_name='work_order')
    op.drop_index('ix_work_order_property_id', table_name='work_order')
    op.drop_index('ix_work_order_company_id_status', table_name='work_order')
    op.drop_index(op.f('ix_work_order_company_id'), table_name='work_order')
    op.drop_table('work_order')
    op.drop_index('ix_employee_registry_employee_id', table_name='employee_registry')
    op.drop_index(op.f('ix_employee_registry_company_id'), table_name='employee_registry')
    op.drop_table('employee_registry')
    op.drop_index('ix_property_customer_id', table_name='property')
    op.drop_index(op.f('ix_property_company_id'), table_name='property')
    op.drop_table('property')
    op.drop_index(op.f('ix_employee_user_id'), table_name='employee')
    op.drop_index('ix_employee_team_id', table_name='employee')
    op.drop_index(op.f('ix_employee_company_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_team_company_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_service_company_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_schedule_company_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_customer_company_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('auth')
    op.drop_table('users')
    op.drop_table('company')
    # ### end Alembic commands ###
