"""add invitation and token tables, employee permission

Revision ID: c067684d10b3
Revises: 05ec64d9ea5c
Create Date: 2026-09-30 18:48:34.439004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c067684d10b3'
down_revision: Union[str, Sequence[str], None] = '05ec64d9ea5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_token_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index(op.f('ix_refresh_token_family_id'), 'refresh_token', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('user_token',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='token_purpose', native_enum=False, length=30), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("purpose IN ('email_verification', 'password_reset')", name=op.f('ck_user_token_purpose_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_token_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_token_token_hash'))
    )
    op.create_index('ix_user_token_user_id_purpose', 'user_token', ['user_id', 'purpose'], unique=False)
    op.create_table('invitation',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_by', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('permission', sa.Enum('owner', 'admin', 'member', name='employee_permission', native_enum=False, length=20), server_default='member', nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("permission <> 'owner'", name=op.f('ck_invitation_not_owner')),
    sa.CheckConstraint("permission IN ('owner', 'admin', 'member')", name=op.f('ck_invitation_permission_valid')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_invitation_email_lowercase')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_invitation_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by', 'company_id'], ['employee.id', 'employee.company_id'], name='fk_invitation_inviter_same_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('public_id', name=op.f('uq_invitation_public_id')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    op.create_index(op.f('ix_invitation_company_id'), 'invitation', ['company_id'], unique=False)
    op.create_index('ix_invitation_invited_by', 'invitation', ['invited_by'], unique=False)
    op.create_index('uq_invitation_pending_company_id_email', 'invitation', ['company_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL'))
    op.add_column('employee', sa.Column('permission', sa.Enum('owner', 'admin', 'member', name='employee_permission', native_enum=False, length=20), server_default='member', nullable=True))
    op.drop_index(op.f('ix_employee_user_id'), table_name='employee')
    op.drop_constraint(op.f('uq_employee_user_id_company_id'), 'employee', type_='unique')
    op.create_index('uq_employee_company_id_owner', 'employee', ['company_id'], unique=True, postgresql_where=sa.text("permission = 'owner'"))
    op.create_unique_constraint('uq_employee_user_id', 'employee', ['user_id'])
    # ### end Alembic commands ###

    # Added by hand: autogenerate does not detect CHECK constraints that are
    # added to tables which already exist.
    op.create_check_constraint(
        op.f('ck_employee_permission_valid'), 'employee',
        "permission IN ('owner', 'admin', 'member')",
    )
    op.create_check_constraint(
        op.f('ck_auth_email_lowercase'), 'auth', 'email = lower(email)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_auth_email_lowercase'), 'auth', type_='check')
    op.drop_constraint(op.f('ck_employee_permission_valid'), 'employee', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_user_id', 'employee', type_='unique')
    op.drop_index('uq_employee_company_id_owner', table_name='employee', postgresql_where=sa.text("permission = 'owner'"))
    op.create_unique_constraint(op.f('uq_employee_user_id_company_id'), 'employee', ['user_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_employee_user_id'), 'employee', ['user_id'], unique=False)
    op.drop_column('employee', 'permission')
    op.drop_index('uq_invitation_pending_company_id_email', table_name='invitation', postgresql_where=sa.text('accepted_at IS NULL'))
    op.drop_index('ix_invitation_invited_by', table_name='invitation')
    op.drop_index(op.f('ix_invitation_company_id'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index('ix_user_token_user_id_purpose', table_name='user_token')
    op.drop_table('user_token')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_family_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
